export const INITIAL_BATTLE_STATE = 'INITIAL_BATTLE_STATE';
export type INITIAL_BATTLE_STATE = typeof INITIAL_BATTLE_STATE;

export const UPDATE_BATTLE_STATE = 'UPDATE_BATTLE_STATE';
export type UPDATE_BATTLE_STATE = typeof UPDATE_BATTLE_STATE;

export const REQUEST_DECISION = 'REQUEST_DECISION';
export type REQUEST_DECISION = typeof REQUEST_DECISION;

export const DECISON_ERROR = 'DECISON_ERROR';
export type DECISON_ERROR = typeof DECISON_ERROR;
